-- Rule definitions matching the default rule set in repo-governor-core.
INSERT INTO rules (rule_key, title, description, category, severity) VALUES
('repo.readme.exists', 'README.md is present', 'Every repository needs a README as its entry point.', 'REPO_HEALTH', 'MAJOR'),
('repo.gitignore.exists', '.gitignore is present', 'A .gitignore prevents build output and local files from being committed.', 'REPO_HEALTH', 'MAJOR'),
('repo.codeowners.exists', 'CODEOWNERS is present', 'CODEOWNERS makes review responsibility explicit.', 'REPO_HEALTH', 'MINOR'),
('repo.license.exists', 'LICENSE is present', 'A license clarifies how the code may be used.', 'REPO_HEALTH', 'MINOR'),
('repo.governor-config.exists', 'repo-governor.yml is present', 'A repo-governor.yml pins project metadata and rule configuration.', 'REPO_HEALTH', 'INFO'),
('java.tests.exist', 'Java test sources are present', 'A Java project should have a src/test/java folder with tests.', 'JAVA', 'MAJOR'),
('java.junit.exists', 'JUnit dependency is declared', 'Build files should declare a JUnit dependency.', 'JAVA', 'MAJOR'),
('java.archunit.exists', 'ArchUnit dependency is declared', 'Build files should declare an ArchUnit dependency.', 'JAVA', 'MINOR'),
('spring.config.exists', 'Spring Boot configuration file is present', 'A Spring Boot application should have an application.yml or application.properties.', 'SPRING_BOOT', 'MINOR'),
('spring.controller.no-direct-repository', 'Controllers should not use repositories directly', 'Controllers that inject repositories bypass the service layer.', 'SPRING_BOOT', 'MAJOR'),
('angular.config.exists', 'angular.json is present', 'An Angular workspace needs an angular.json.', 'ANGULAR', 'MAJOR'),
('angular.src-app.exists', 'src/app folder is present', 'Angular application code is expected under src/app.', 'ANGULAR', 'MAJOR'),
('angular.standalone.components', 'Angular project uses standalone components', 'Modern Angular projects should use standalone components instead of NgModules.', 'ANGULAR', 'MINOR'),
('angular.signals.used', 'Angular signals are used for state', 'Angular projects should manage local state with signals.', 'ANGULAR', 'INFO'),
('api.openapi.exists', 'OpenAPI specification is present', 'Services should describe their API with an OpenAPI contract.', 'API_CONTRACT', 'MAJOR'),
('cicd.pipeline.exists', 'CI pipeline is configured', 'Every repository should be built and tested by a CI pipeline.', 'CI_CD', 'MAJOR'),
('cicd.test-step.exists', 'CI pipeline runs tests', 'The CI pipeline should run the test suite on every change.', 'CI_CD', 'MAJOR'),
('security.dependency-updates.configured', 'Automated dependency updates are configured', 'Dependabot or Renovate keeps dependencies patched.', 'SECURITY', 'MAJOR'),
('security.env.not-committed', 'No .env file committed', '.env files typically contain secrets and must never be committed.', 'SECURITY', 'BLOCKER'),
('security.secrets.in-config', 'No hard-coded secrets in configuration files', 'Configuration files should not contain secret literals.', 'SECURITY', 'MAJOR'),
('ai.copilot-instructions.exists', 'Copilot instructions are present', 'AI coding assistants work better with repository-specific instructions.', 'AI_READINESS', 'MINOR'),
('ai.agents-file.exists', 'Agent instructions are present', 'An AGENTS.md (or CLAUDE.md) helps AI agents navigate the repository.', 'AI_READINESS', 'MINOR'),
('docs.folder.exists', 'docs folder is present', 'Larger design documentation belongs in a docs/ folder.', 'DOCUMENTATION', 'INFO'),
('docs.readme.sections', 'README explains install, run and test', 'The README should contain installation, run and test instructions.', 'DOCUMENTATION', 'MINOR');
